---
apiVersion: projectriff.io/v1alpha1
kind: Invoker
metadata:
  name: command
spec:
  version: 0.0.8-snapshot
  matchers:
  - "*"
  functionTemplate:
    spec:
      protocol: http
  files:
  - path: Dockerfile
    template: |
      FROM projectriff/command-function-invoker:{{.InvokerVersion}}
      RUN mkdir /functions
      ADD {{.Artifact}} /functions/
      ENV FUNCTION_URI /functions/{{.ArtifactBase}}
  doc: |
    {{.Process}} the function based on the executable command specified as the filename, using the name
    and version specified for the function image repository and tag.
    
    For example, from a directory named 'echo' containing a function 'echo.sh', you can simply type :
    
        riff {{.Command}} -a echo.sh
    
    to {{.Result}}.
